# cloudbuild.yaml for efficient Docker builds with persistent cache refresh

options:
  machineType: E2_HIGHCPU_8
  env:
    - DOCKER_BUILDKIT=1
    - BUILDKIT_INLINE_CACHE=1

steps:
  # Step 1: Pull the cache image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - pull
      - gcr.io/$PROJECT_ID/concepter-web:cache-prime

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--tag=gcr.io/$PROJECT_ID/concepter-web:$COMMIT_SHA'
      - '--tag=gcr.io/$PROJECT_ID/concepter-web:cache-prime'
      - '--cache-from=gcr.io/$PROJECT_ID/concepter-web:cache-prime'
      - '--build-arg=BUILDKIT_INLINE_CACHE=1'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/concepter-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/concepter-web:cache-prime'
