gantt
  title Gantt Diagram for Strategy2030
  dateFormat YYYY-MM-DD

  section Goal 1
    Progress: Largiebaan as an example of how our wildlife reserves are contributing to nature’s recovery, given that we’ve seen important progress after years of challenges on this site :b5acd5cf-1b6f-4871-8e7b-92291e01b16a, 2025-06-06, 14d
    Challenges: Something about how we’d like to get better at measuring and monitoring on our reserves – and how we’ve taken action to address this challenge? :6fff0346-9591-4a22-8e86-4526325e5593, 2025-06-06, 14d

  section Goal 2:
    Progress: Something about how our work on Nextdoor Nature, and our wider engagement strategy, are helping us to reach new audiences, using the multiplier effect. :b49beb06-b5a5-4245-a401-416de125e673, 2025-06-06, 14d
    Challenges: The challenges of taking this to scale and how we’re exploring options for to achieve ever greater impact? :a4d3d1b0-66cc-42fd-8542-ad3195bc0d92, 2025-06-06, 14d

  section Goal 3:
    Progress: Some of the recent successes in bringing Riverwoods partners together to start delivering the Scotland-wide Riverwoods vision :78090e28-7d4b-4c9a-92d4-c3d63636ad1a, 2025-06-06, 14d
    Challenges: The difficulties associated with long-term visions and short-term funding, and how we’re responding to that :eef46b47-acbb-42b2-b527-8b3f8835ff72, 2025-06-06, 14d

  section Goal 4:
    Progress: Some of the policy wins and positive direction of travel that we’ve seen since the beginning of Strategy 2030, with the development of the Scottish Biodiversity Strategy and current progress of the Natural Environment Bill (explaining to staff why this is important) :6474e3e2-d95c-4e0f-9c44-5ce9fd3929e5, 2025-06-06, 14d
    Challenges: Recognition of the fact that the environment is being pushed down the agenda by other topics and how we’re responding to this (including our ‘cost of inaction’ report) :b9290dd6-51a6-4a8c-9c46-cefcefe67b2e, 2025-06-06, 14d

  section Goal 5:
    Progress: I think we ought to celebrate that the Trust remains in good financial health and is delivering across a wide range of activities, despite the many pressures on our sector :6f27dfb4-8399-4dbf-b0d3-a32c7a102355, 2025-06-06, 14d
    Challenges: Pressure on our core capacity and how we’re responding, including arrangements to improve ICT support, exploration of how strategic partnerships can extend our capacity and so on :92ff4308-c66f-4356-886d-9e3e32b1c7e4, 2025-06-06, 14d
